Error#0@2020-02-12 14h38.09.8725675
UnhandledException
 ┌──────────────────────────■ Exception : Exception ■──────────────────────────
 | Message: Unhandled exception, directly on the thread pool, during the timer handling.
 | Stack:    at Front.App.LoggerTestHostedService.OnTime(Object state) in C:\Dev\CK\CK-Database-Projects\CK-Sample-MultiBinPath\Front.App\LoggerTestHostedService.cs:line 72
 |           at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
 |           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
 |        --- End of stack trace from previous location where exception was thrown ---
 |           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
 |           at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
 |           at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
 |           at System.Threading.TimerQueue.FireNextTimers()
 |           at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
 └─────────────────────────────────────────────────────────────────────────────
